### ISSUE TITLE
Timestams on catched stats get mangled.

### ISSUE THREAD

**Issue by Wojbie** [Lemmmy/shitty.dl#8]
Hey i just noticed that time-stamps get mangled on loading from JSON file after restarting shitty.dl.
Before:
![obraz](https://user-images.githubusercontent.com/5893536/38280407-69e39ae2-37a5-11e8-82a9-eabd43366870.png)
![obraz](https://user-images.githubusercontent.com/5893536/38280412-6ddfa0fa-37a5-11e8-9223-40e56d661a51.png)
After:
![obraz](https://user-images.githubusercontent.com/5893536/38280418-70c84b6e-37a5-11e8-8e52-d0200216ee35.png)
![obraz](https://user-images.githubusercontent.com/5893536/38280420-73dd8526-37a5-11e8-928c-23afabe591d9.png)
As you can see in last image the newly uploaded file has correct time-stamp. That means something gets messed up in JSON save and reload.

**Comment by Lemmmy** [comment]
https://github.com/Lemmmy/shitty.dl/blob/master/index.js#L257

![](https://nodejs.org/api/fs.html#fs_stats_mtime) mtime is a Date object - serialise this properly

**Comment by Lemmmy** [comment]
@Lignum ur gay pwned

**Comment by Wojbie** [comment]
Wait what does Lignum got to do with any of this?

**Comment by Lignum** [comment]
I am also wondering about that, however I despise that phrase, hence it is beneficial for @Lemmmy to mention it fucking everywhere like a retard.
